version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Instalando dependencias...
      - npm install
  build:
    commands:
      - echo Iniciando o build do React...
      - npm run build
  post_build:
    commands:
      - aws s3 sync dist/ s3://$BUCKET_NAME/ --delete
      - aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
artifacts:
  base-directory: dist
  files:
    - "**/*"
