AWSTemplateFormatVersion: '2010-09-09'
Description: Fase 1 - Bucket S3 Privado para Portfolio

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Gera um nome unico usando o ID da conta
      BucketName: !Sub "portfolio-${AWS::AccountId}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Value: !Ref SiteBucket